### PR TITLE
Fix test

### LINKED ISSUE #19: decompressRandom test failure
I used `stack unpack lzma-conduit-1.2.1` then `echo -e "resolver: lts-13.0" > stack.yaml`. With that I get the following:
```
qrilka@qdesktop ~/ws/h/lzma-conduit-1.2.1 $ stack test --ta="--test-seed=-3697173464033279494"
lzma-conduit-1.2.1: test (suite: lzma-test, args: --test-seed=-3697173464033279494)

Compress:
  compressAndDiscard: [OK, passed 100 tests]
  compressAndCheckLength: [OK, passed 100 tests]
Decompress:
  decompressRandom: [Failed]
*** Failed! Assertion failed (after 75 tests):
""
(used seed -3697173464033279494)
  decompressCorrupt: [OK, passed 100 tests]
  decompressEmpty: [OK, passed 100 tests]
Chained:
  chain: [OK, passed 100 tests]
  compressThenDecompress: [OK, passed 100 tests]

         Properties  Total      
 Passed  6           6          
 Failed  1           1          
 Total   7           7          

lzma-conduit-1.2.1: Test suite lzma-test failed
Test suite failure for package lzma-conduit-1.2.1
    lzma-test:  exited with: ExitFailure 1
Logs printed to console
```

### PR DESCRIPTION
**Pull request by luispedro**
Fixes #19

### CODE REVIEW

File: tests/Main.hs [hunk 1]
```diff
@@ -73,6 +73,9 @@ prop_compressThenDecompress = monadicIO . forAllM someBigString $ \ str -> do
 
 prop_decompressRandom :: Property
 prop_decompressRandom = monadicIO . forAllM someBigString $ \ str -> do
+  -- The someBigString is not necessarily big. It can even be the empty string
+  -- https://github.com/alphaHeavy/lzma-conduit/issues/19
+  pre $ B.length str > 64
```
Comment (NathanHowell) [inline tests/Main.hs:78]: does it need to be >64? would any length above zero work?

```suggestion
  pre $ B.length str > 0
```

Comment (luispedro) [reply tests/Main.hs:78]: I don't know the format of the files at all. How unlikely is it to randomly generate a valid 2 or 3 Byte file? So, I figured that 64 was large enough that a randomly generated 64 Byte file was never going to be valid.

Comment (NathanHowell) [reply tests/Main.hs:78]: good point, seems like a reasonable tradeoff
